### ISSUE TITLE
Update our tech radar

### ISSUE THREAD

**Issue by mxauriga** [FlexPwr/FlexTeXRadar#1]
- [x] Update the items in our Radar ruffly 
- [x] Give it to the team to Update the descriptions and discuss together
- [ ] pubish it
- [ ] write a blog post
- [ ] find a routine to update it constantly

**Comment by mxauriga** [comment]
I managed to publish the radar and descriped the process in the readMe.

Here is it: https://radar.thoughtworks.com/?documentId=https://raw.githubusercontent.com/FlexPwr/FlexTeXRadar/main/content/FlexPwrTechRadar%20-%202024.1.json 

now we can start updating and editing the config. the link stays the same. the documentID is part of the link. ;-)

I found a action that publishes a radar to github pages. i added the code but it is not yet working.

**Comment by malwini** [comment]
@mxauriga should we close this one for now? Do you have a link where we can see the current radar?

I suggest we plan a new session in July and do a bit more refinement.
